
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: bronze_1g
    description: "inocircle snowflake example tables"
    tables:
      - name: customers
        columns:
          - name: c_customer_sk
            description: "customer sk"
            tests:
              - not_null
          - name: c_customer_id
            description: "customer id"
            tests:
              - unique
              - not_null
          - name: c_current_addr_sk
            description: "current address"
            tests:
              - not_null
          - name: c_first_name
            description: "first name"
            tests:
              - not_null
          - name: c_last_name
            description: "last name"
            tests:
              - not_null
          - name: c_preferred_cust_flag
            description: "customer flag"
            tests:
              - not_null
          - name: c_birth_day
            description: "day of birth"
            tests:
              - not_null
          - name: c_birth_month
            description: "month of birth"
            tests:
              - not_null
          - name: c_birth_year
            description: "year of birth"
            tests:
              - not_null
          - name: c_birth_country
            description: "country of birth"
            tests:
              - not_null
          - name: c_login
            description: "login"
            tests:
              - not_null
          - name: c_email_address
            description: "email address"
            tests:
              - not_null

